const USER_STATUS = {
  INVITED: 'INVITED',
  ACTIVE: 'ACTIVE',
  DEACTIVATED: 'DEACTIVATED',
};

const USER_ROLE = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  OWNER: 'OWNER',
};

const SCHEDULE_PERMISSIONS = {
  GET: 'GET',
  POST: 'POST',
  PATCH: 'PATCH',
  DELETE: 'DELETE',
};

module.exports = { USER_STATUS, USER_ROLE, SCHEDULE_PERMISSIONS };
