const VISIT_RECURRING = {
  ONE_OFF: 'ONE_OFF',
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
};

const VISIT_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

module.exports = { VISIT_RECURRING, VISIT_STATUS };
